SOURCE = '~/MATLAB/datasets_all/multispectral';
MATSOURCE = '~/MATLAB/sparse_linear_model/hyperspectral/ms_matfiles';
TARGET = '~/MATLAB/sparse_linear_model/hyperspectral/ms_figures_norm';
fileNames = {...
	'balloons_ms',...
	'beads_ms'...
	'sponges_ms',...
	'oil_painting_ms',...
	'flowers_ms',...
	'cd_ms',...
	'fake_and_real_peppers_ms',...
	'photo_and_face_ms',...
	'thread_spools_ms',...
	'clay_ms',...
	'fake_and_real_lemons_ms',...
	'glass_tiles_ms',...
	'real_and_fake_apples_ms',...
	'watercolors_ms',...
	'cloth_ms',...
	'hairs_ms',...
	'real_and_fake_peppers_ms',...
	'egyptian_statue_ms',...
	'fake_and_real_strawberries_ms',...
	'jelly_beans_ms',...
	'face_ms',...
	'fake_and_real_sushi_ms',...
	'fake_and_real_beers_ms',...
	'fake_and_real_tomatoes_ms',...
	'paints_ms',...
	'stuffed_toys_ms',...
	'fake_and_real_food_ms',...
	'feathers_ms',...
	'superballs_ms',...
	'chart_and_stuffed_toy_ms',...
	'fake_and_real_lemon_slices_ms',...
	'pompoms_ms',...
	};

largeM = 512;
largeN = 512;
samplingFactor = 1;
tau = 20;
wavelengths = 400:10:700;
Y = getKernelFactor(wavelengths, tau);
W = eye(31);
% psVec = [0.05 0.1 0.2];
psVec = [0.1];
M = largeM / 2 ^ samplingFactor;
N = largeN / 2 ^ samplingFactor;

numFiles = length(fileNames);
numPs = length(psVec);
MSE = zeros(2 * length(psVec), numFiles);

for iterFiles = 1:numFiles,
	fprintf('Now running file %s, number %d out of %d.\n', fileNames{iterFiles}, iterFiles, numFiles);
	cube = getCube(sprintf('%s/%s/%s', SOURCE, fileNames{iterFiles}, fileNames{iterFiles}), 'png', 1:31, 0);
	cube = cube / maxv(cube);
	cubedown = downSampleCube(cube, samplingFactor);
	maxcube = maxv(cubedown) * 4;
	rgbIm = cube2rgb2(cubedown)/maxcube;
% 	figure; imshow(rgbIm)
% 	eval(sprintf('print -depsc2 %s/%s_sub%d_orig.eps', TARGET, fileNames{iterFiles}, samplingFactor));
% 	eval(sprintf('imwrite(rgbIm, ''%s/%s_sub%d_orig.png'')', TARGET, fileNames{iterFiles}, samplingFactor));
% 	close
	for iterPs = 1:numPs,
		ps = psVec(iterPs);
		load(sprintf('%s/robust_pca_ps%g_def_%s_sub%d.mat', MATSOURCE, ps,...
			fileNames{iterFiles}, samplingFactor),...
			'cube_background', 'noisevec');
		
		cubedownnoise = cubedown + reshape(noisevec, size(cubedown));
		rgbIm = cube2rgb2(cubedownnoise)/maxcube;
% 		figure; imshow(rgbIm / maxv(rgbIm));
% 		eval(sprintf('print -depsc2 %s/%s_sub%d_ps%g_noisy.eps', TARGET, fileNames{iterFiles}, samplingFactor, ps));
% 		eval(sprintf('imwrite(rgbIm / maxv(rgbIm), ''%s/%s_sub%d_ps%g_noisy.png'')', TARGET, fileNames{iterFiles}, samplingFactor, ps));
% 		close
		
		MSE((iterPs - 1) * 2 + 1, iterFiles) = sum((cubedown(:) - cube_background(:)) .^ 2) / numel(cubedown);
		rgbIm = cube2rgb2(cube_background)/maxcube;
% 		figure; imshow(rgbIm);
% 		eval(sprintf('print -depsc2 %s/%s_sub%d_ps%g_pca.eps', TARGET, fileNames{iterFiles}, samplingFactor, ps));
% 		eval(sprintf('imwrite(rgbIm, ''%s/%s_sub%d_ps%g_pca.png'')', TARGET, fileNames{iterFiles}, samplingFactor, ps));
% 		close
		
		errorImg = sqrt(sum((cubedown - cube_background).^2,3));
% 		figure; imshow(errorImg); colormap jet
% 		eval(sprintf('print -depsc2 %s/%s_sub%d_ps%g_pca_error.eps', TARGET, fileNames{iterFiles}, samplingFactor, ps));
		eval(sprintf('imwrite(im2uint8(errorImg), jet(256), ''%s/%s_sub%d_ps%g_pca_error.png'')', TARGET, fileNames{iterFiles}, samplingFactor, ps));
		close
		
		load(sprintf('%s/robust_oppca_ps%g_tau%g_def_%s_sub%d.mat', MATSOURCE, ps, tau,...
		fileNames{iterFiles}, samplingFactor),...
		'cube_background');
		cube1 = applyKernelFactor(cube_background, Y);
		MSE((iterPs - 1) * 2 + 2, iterFiles) = sum((cubedown(:) - cube1(:)) .^ 2) / numel(cubedown);
		rgbIm = cube2rgb2(cube1)/maxcube;
% 		figure; imshow(rgbIm)
% 		eval(sprintf('print -depsc2 %s/%s_sub%d_ps%g_oppca%g.eps', TARGET, fileNames{iterFiles}, samplingFactor, ps, tau));
% 		eval(sprintf('imwrite(rgbIm, ''%s/%s_sub%d_ps%g_oppca%g.png'')', TARGET, fileNames{iterFiles}, samplingFactor, ps, tau));
% 		close

		errorImg = sqrt(sum((cubedown - cube1).^2,3));
% 		figure; imshow(errorImg); colormap jet
% 		eval(sprintf('print -depsc2 %s/%s_sub%d_ps%g_oppca%g_error.eps', TARGET, fileNames{iterFiles}, samplingFactor, ps, tau));
		eval(sprintf('imwrite(im2uint8(errorImg), jet(256), ''%s/%s_sub%d_ps%g_oppca%g_error.png'')', TARGET, fileNames{iterFiles}, samplingFactor, ps, tau));
		close
	end
end;
